### ISSUE TITLE
Možnost spravovat subgroupy adminem

### ISSUE THREAD

**Issue by manhhungtran** [romcooo/jana-bot#6]
Správa subgroup 
(přidávat-odebírat) osoby ze skupiny. 

Example:
```
/group -kick <group> <username>
/group -join <group> <username>
/group -rename <group> <newname>
```

**Comment by romcooo** [comment]
-kick a -rename done v #15

**Comment by filipceko** [comment]
#16 -add functional for chat admins (meaning they have to have the admin role enabled within the chat), this is required to be able to verify if the user to be added is actually a chat member. Telegram API does not provide any other means to access chat members.
